/**
 * pg-boss Fastify plugin — Phase 15 Plan 05, Task 5.2.
 *
 * Ships the v3.0 queue substrate:
 *   - Starts pg-boss v12 against Postgres with the default `pgboss` schema (isolated
 *     from app tables; auto-migrates on first run, idempotent thereafter).
 *   - Decorates `fastify.boss` (raw PgBoss instance) and `fastify.queue` (thin ALS-aware
 *     send/work/schedule wrapper) so downstream module phases have one producer and
 *     one consumer API.
 *   - Solves the cross-queue ALS gotcha (RESEARCH §3): `queue.send` serialises
 *     correlationId / causationId / actor from the active ALS store into `job.data`,
 *     and `queue.work` restores a Map-shaped ALS store on the worker fiber BEFORE
 *     invoking the user handler.
 *   - Registers an `onClose` hook that calls `boss.stop({ graceful: true, timeout: 30_000 })`
 *     so Fastify's shutdown chain drains workers within the K8s-default 30s window
 *     (QUEUE-07).
 *
 * The plugin creates only the `DEMO` queue itself. Real module queues (`job.execute`,
 * `webhook.deliver`, ...) will be registered by each module's own `queue.ts` in
 * Phase 16+ via `fastify.boss.createQueue(...)`.
 *
 * Satisfies: QUEUE-01, QUEUE-02, QUEUE-04, QUEUE-07, TRACE-05.
 */
import fp from 'fastify-plugin';
import { PgBoss } from 'pg-boss';
import { randomUUID } from 'node:crypto';
import { requestContext, asyncLocalStorage } from '@fastify/request-context';
import { QUEUE_NAMES, isValidQueueName } from './names.js';

/** Public interface the wrapper exposes on `fastify.queue`. */
interface QueueApi {
  /** Enqueue a job. Returns pg-boss's jobId, or null when the queue is full. */
  send: (
    name: string,
    data: unknown,
    opts?: Record<string, unknown>,
  ) => Promise<string | null>;
  /**
   * Register a worker. Restores ALS (correlationId / causationId / actor) from
   * `job.data` BEFORE invoking the handler, so `requestContext.get('correlationId')`
   * and the pino mixin work inside the handler as if we were still on the request fiber.
   */
  work: <T = unknown>(
    name: string,
    handler: (data: T, jobId: string) => Promise<void> | void,
  ) => Promise<string>;
  /**
   * Schedule a recurring job. The wrapper stores the envelope with
   * `correlationId: null` so each dispatched fire gets a fresh UUID
   * generated by `queue.work` (actor='cron' stamped at schedule time).
   * Per-fire trace isolation — see Phase 18 RESEARCH §Enqueue Wrapper
   * Design, Option B.
   */
  schedule: (
    name: string,
    cron: string,
    data?: unknown,
    opts?: Record<string, unknown>,
  ) => Promise<void>;
}

declare module 'fastify' {
  interface FastifyInstance {
    boss: PgBoss;
    queue: QueueApi;
  }
}

/** Shape of the envelope the wrapper wraps around the caller's payload. */
interface JobEnvelope {
  /**
   * For `queue.send`: the caller's ALS-derived correlationId (UUID string).
   * For `queue.schedule`: always `null` — Phase 18 Option B per-fire behaviour,
   * `queue.work` generates a fresh UUID on each dispatched fire so scheduled
   * jobs get trace-isolation instead of inheriting ONE id.
   */
  correlationId: string | null;
  causationId: string | null;
  actor: string;
  payload: unknown;
}

/**
 * Read a value from whatever ALS store shape is active (Map — queue-restored fiber,
 * or object — request-context fiber). Falls back to null on anything else.
 */
function readStore(store: unknown, key: string): unknown {
  if (!store) return null;
  if (store instanceof Map) return store.get(key) ?? null;
  if (typeof store === 'object') return (store as Record<string, unknown>)[key] ?? null;
  return null;
}

/** Plugin options — only used by tests today to isolate the Postgres schema. */
interface QueuePluginOptions {
  /**
   * Override the Postgres schema name pg-boss uses. Production leaves this
   * unset (defaults to `'pgboss'` per plan 15 convention). Tests pass a
   * file-unique schema so parallel Vitest files don't stomp on each other.
   */
  schema?: string;
  /**
   * Override pg-boss's `cronMonitorIntervalSeconds` (default 30s, valid 1-45s).
   * Production leaves this unset. Integration tests that need to observe
   * cron-dispatched schedule fires within a bounded timeout (e.g.
   * `server/lifecycle/__tests__/correlation.spec.ts` using `* * * * * *`)
   * pass a low value (typically 1s) so cron monitoring fires within the test
   * window. See RESEARCH §pg-boss Schedule API.
   */
  cronMonitorIntervalSeconds?: number;
  /**
   * Override pg-boss's `maintenanceIntervalSeconds` (default 60s). Production
   * leaves this unset. Integration tests that need to observe dead-letter
   * re-insertion within a bounded timeout (e.g.
   * `server/reporting/__tests__/queue.spec.ts` proving SC1 5× 500 → DLQ)
   * pass a low value (typically 1s) because pg-boss's failed_jobs CTE that
   * re-inserts exhausted payloads into the DLQ queue runs inside the
   * maintenance loop (see Phase 19 RESEARCH §Pitfall 1 —
   * node_modules/pg-boss/dist/plans.js:1090-1168).
   */
  maintenanceIntervalSeconds?: number;
}

export default fp<QueuePluginOptions>(async function queuePlugin(fastify, opts) {
  const connectionString = fastify.config.database_url;
  // Production default: schema: 'pgboss'. Tests may override via opts.schema.
  const schema = opts.schema ?? 'pgboss';

  const boss = new PgBoss({
    connectionString,
    schema,
    application_name: 'device-farm-server',
    ...(opts.cronMonitorIntervalSeconds !== undefined
      ? { cronMonitorIntervalSeconds: opts.cronMonitorIntervalSeconds }
      : {}),
    ...(opts.maintenanceIntervalSeconds !== undefined
      ? { maintenanceIntervalSeconds: opts.maintenanceIntervalSeconds }
      : {}),
  } as never);

  // Attach error listener BEFORE start so bootstrap errors get logged.
  boss.on('error', (err) => fastify.log.error({ err }, 'pg-boss internal error'));

  await boss.start();
  fastify.log.info({ schema }, 'pg-boss started');

  // Phase 15 registers ONLY the DEMO queue with the physical-side-effect retry default.
  // Module phases (16+) will register their own queues in their local queue.ts files.
  // retryLimit: 1 is the conservative default for handlers with physical side effects
  // (see RESEARCH §1 + QUEUE-04). Callers can override per-send via opts.retryLimit.
  await boss.createQueue(QUEUE_NAMES.DEMO, {
    retryLimit: 1,
    retryBackoff: true,
    retryDelay: 30,
  } as never);

  fastify.decorate('boss', boss);

  fastify.decorate('queue', {
    async send(name, data, opts = {}) {
      if (!isValidQueueName(name)) {
        throw new Error(`Invalid queue name: ${name}`);
      }
      // Read ALS — the active store may be either the request-context object OR a
      // queue-restored Map (if send is called from another worker). Fall back to
      // a fresh UUID when there is no active store (unscoped caller).
      const store = asyncLocalStorage.getStore();
      const correlationId =
        (readStore(store, 'correlationId') as string | null) ?? randomUUID();
      const causationId = (readStore(store, 'currentEventId') as string | null) ?? null;
      const actor = (readStore(store, 'actor') as string | null) ?? 'system';

      const envelope: JobEnvelope = { correlationId, causationId, actor, payload: data };
      return boss.send(name, envelope, opts);
    },

    async work<T = unknown>(
      name: string,
      handler: (data: T, jobId: string) => Promise<void> | void,
    ) {
      if (!isValidQueueName(name)) {
        throw new Error(`Invalid queue name: ${name}`);
      }
      return boss.work(name, async (jobs: unknown) => {
        // pg-boss v12 invokes the handler with an array of jobs (batch-aware API).
        // We normalise to a single job here — Phase 15 does not exercise batching.
        const job = Array.isArray(jobs) ? jobs[0] : jobs;
        const data = (job as { data?: Partial<JobEnvelope> }).data ?? {};
        const id = (job as { id: string }).id;

        // The ALS store MUST be an object, not a Map: `@fastify/request-context`'s
        // `requestContext.get(key)` reads `store[key]` directly. A Map would work for
        // the pino `alsMixin` (shape-agnostic) but would silently fail for any
        // worker code that calls `requestContext.get(...)`. Research §3 showed a
        // Map pattern; we upgrade to the object shape so both readers work.
        const store: Record<string, unknown> = {
          correlationId: data.correlationId ?? randomUUID(),
          currentEventId: data.causationId ?? null,
          actor: data.actor ?? 'cron',
        };

        // `@fastify/request-context` types `asyncLocalStorage` narrowly as
        // `AsyncLocalStorage<RequestContext>` even though the library itself stores
        // a plain object of defaultStoreValues. Cast here to match runtime behaviour.
        await asyncLocalStorage.run(store as never, async () => {
          await handler(data.payload as T, id);
        });
      });
    },

    async schedule(name, cron, data = {}, opts = {}) {
      if (!isValidQueueName(name)) {
        throw new Error(`Invalid queue name: ${name}`);
      }
      // Phase 18 / QUEUE-08 — Option B per-fire correlationId:
      // Store the envelope with correlationId:null so that queue.work generates
      // a fresh randomUUID() on every dispatched fire (line 159 already has the
      // `data.correlationId ?? randomUUID()` fallback). Stamping a UUID here
      // would cause every scheduled fire to inherit ONE id — see RESEARCH §Pitfall 3.
      const envelope: JobEnvelope = {
        correlationId: null,
        causationId: null,
        actor: 'cron',
        payload: data,
      };
      await boss.schedule(name, cron, envelope as never, opts);
    },
  } satisfies QueueApi);

  // Wire graceful shutdown — Fastify's onClose runs plugins in reverse order, so
  // `queue.onClose` fires BEFORE `db.onClose` (the connection pool is still alive
  // when we stop boss, which pg-boss v12.15 requires for maintenance drain).
  fastify.addHook('onClose', async () => {
    fastify.log.info('pg-boss: stopping (graceful, timeout=30s)...');
    await boss.stop({ graceful: true, timeout: 30_000, destroy: false } as never);
    fastify.log.info('pg-boss: stopped');
  });

  // Passively used: correlation is declared to enforce registration ordering, but
  // the plugin itself never imports from server/correlation — requestContext /
  // asyncLocalStorage come directly from @fastify/request-context.
  void requestContext;
}, { name: 'queue', dependencies: ['db', 'correlation'] });
