<script lang="ts">
	/**
	 * Monaco-backed TypeScript editor for `kind: 'script'` hooks.
	 *
	 * Loads the @device-stream/dsl `.d.ts` surface into the TypeScript language
	 * service plus an ambient prelude that declares `ds`, `vars`, `ctx`, `console`
	 * as globals — this mirrors the wrapper that server/hooks/internal/script-runner.ts
	 * generates at execution time, so what the user writes here type-checks the same
	 * way it will run.
	 *
	 * Monaco only runs in the browser; SSR is skipped via `if (!browser) return`.
	 */
	import { browser } from '$app/environment';
	import { onDestroy } from 'svelte';

	import dslIndexDts from '@device-stream/dsl/dist/index.d.ts?raw';
	import dslTypesDts from '@device-stream/dsl/dist/types.d.ts?raw';

	let {
		value = $bindable(''),
		readonly = false,
		height = '320px',
	}: {
		value?: string;
		readonly?: boolean;
		height?: string;
	} = $props();

	let container: HTMLDivElement | undefined = $state(undefined);
	let editor: any = null;
	let monacoRef: any = null;
	let disposeChangeListener: { dispose: () => void } | null = null;

	const AMBIENT_PRELUDE = `
		// Ambient declarations matching the prelude generated by script-runner.ts.
		// Lets the user write \`ds.openUrl(url)\` without an import.
		declare const ds: import('@device-stream/dsl').DeviceStreamSession;
		declare const ctx: {
			deviceId: string;
			emulatorId: string;
			serial: string;
			platform: 'android' | 'ios';
			port: number | null;
			jobId?: string;
		};
		declare const vars: Record<string, any>;
		declare const console: { log(...args: any[]): void; warn(...args: any[]): void; error(...args: any[]): void };
	`;

	async function mount() {
		if (!container) return;

		// Vite resolves these new-URL imports to the actual chunk URLs.
		(globalThis as any).MonacoEnvironment = {
			getWorker(_workerId: string, label: string) {
				if (label === 'typescript' || label === 'javascript') {
					return new Worker(
						new URL(
							'monaco-editor/esm/vs/language/typescript/ts.worker.js',
							import.meta.url,
						),
						{ type: 'module' },
					);
				}
				return new Worker(
					new URL('monaco-editor/esm/vs/editor/editor.worker.js', import.meta.url),
					{ type: 'module' },
				);
			},
		};

		const monaco = await import('monaco-editor');
		monacoRef = monaco;

		const ts = monaco.languages.typescript;
		ts.typescriptDefaults.setCompilerOptions({
			target: ts.ScriptTarget.ES2020,
			module: ts.ModuleKind.ESNext,
			moduleResolution: ts.ModuleResolutionKind.NodeJs,
			lib: ['es2020', 'dom'],
			strict: true,
			noEmit: true,
			esModuleInterop: true,
			allowJs: false,
			allowNonTsExtensions: true,
		});
		ts.typescriptDefaults.setDiagnosticsOptions({
			noSemanticValidation: false,
			noSyntaxValidation: false,
			diagnosticCodesToIgnore: [
				1375, // top-level await in CommonJS — we run as ESM .mts
				1378, // top-level await without esnext
			],
		});

		// Register the DSL .d.ts files as virtual files so `import` paths resolve
		// AND the ambient prelude makes `ds`/`vars`/`ctx` available without imports.
		ts.typescriptDefaults.addExtraLib(
			dslTypesDts,
			'file:///node_modules/@device-stream/dsl/dist/types.d.ts',
		);
		ts.typescriptDefaults.addExtraLib(
			dslIndexDts,
			'file:///node_modules/@device-stream/dsl/dist/index.d.ts',
		);
		ts.typescriptDefaults.addExtraLib(AMBIENT_PRELUDE, 'file:///ambient.d.ts');

		const modelUri = monaco.Uri.parse('file:///hook-script.ts');
		const existing = monaco.editor.getModel(modelUri);
		if (existing) existing.dispose();
		const model = monaco.editor.createModel(value, 'typescript', modelUri);

		editor = monaco.editor.create(container, {
			model,
			theme: 'vs-dark',
			fontSize: 13,
			fontFamily:
				'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
			minimap: { enabled: false },
			scrollBeyondLastLine: false,
			automaticLayout: true,
			readOnly: readonly,
			tabSize: 2,
			insertSpaces: true,
			wordWrap: 'on',
			padding: { top: 12, bottom: 12 },
		});

		disposeChangeListener = model.onDidChangeContent(() => {
			value = model.getValue();
		});
	}

	$effect(() => {
		if (!browser) return;
		void mount();
	});

	// Sync prop → editor when the parent rewrites `value` (e.g. switching hooks).
	$effect(() => {
		if (!editor || !monacoRef) return;
		const current = editor.getValue();
		if (current !== value) editor.setValue(value ?? '');
	});

	onDestroy(() => {
		try {
			disposeChangeListener?.dispose();
			editor?.getModel()?.dispose();
			editor?.dispose();
		} catch {
			/* noop */
		}
	});
</script>

<div
	bind:this={container}
	class="rounded-lg overflow-hidden border border-outline-variant/20"
	style:height
></div>
